server:
  port: 8889

##文件映射路径
file:
  uploadPath: /mundaneinn-back-end-plus/upload/admin/      #文件上传路径
  uploadMaxSize: 204800                #单文件上传大小 200M
  downloadPath: /mundaneinn-back-end-plus/download/  #文件下载路径  比如模板文件

spring:
  application:
    name: admin
  #sql配置,访问监控页面http://localhost:8080/druid/login.html
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/mundaneinn-plus?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
      username: root
      password: 19980805kcx
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 50000
      min-evictable-idle-time-millis: 300000
      #Oracle需要打开注释
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: sys
        #login-password: sys
      #配置监控统计拦截的filters，stat:监控统计、log4j：日志记录、wall：防御sql注入
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
          enabled: true
        wall:
          config:
            multi-statement-allow: true
  # redis 配置
  redis:
    # 地址
    host: 127.0.0.1
    # 端口，默认为6379
    port: 6379
